---
- name: Balancer install
  hosts: balancer
  become: true
  gather_facts: true

  tasks:
   - name: Install epel release
     yum:
        name: epel-release
        state: present

   - name: Install nginx
     yum:
        name: nginx
        state: present
     
   - name: Start nginx, if not started
     service:
        name: nginx       
        state: started
        enabled: yes

   - name: Pushes configuration
     template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0640 owner=root group=root
     notify:
       - restart nginx
  
   - name: Start service firewalld, if not started
     service:
      name: firewalld       
      state: started
      enabled: yes    

   - name: Add ssh service firewalld
     firewalld:
       zone: public
       service: ssh
       permanent: yes
       state: enabled
     notify:
       - firewalld reload

   - name: Add http service firewalld
     firewalld:
       zone: public
       port: 80/tcp
       permanent: yes
       state: enabled
     notify:
       - firewalld reload
       
  handlers:
   - name: restart nginx
     service: name=nginx state=restarted

   - name: firewalld reload
     command: firewall-cmd --reload