---
# - hosts: all
#   vars:
#     dbname: moodledb
#     userdb: moodleus
#     userPWD: moodle123

#   tasks:
#   - name: upgrade system

# - hosts: db_server

#   tasks:
#   - name: Add official MariaDB repository
#      yum_repository:
#       name: MariaDB
#       description: Official MariaDB repository
#       baseurl: "http://http://yum.mariadb.org/10.4.3/centos7-amd64/"
#       gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
#       gpgcheck: true
#   tags: mariadb
  
#   - name: install packages
#     yum: pkg={{ item.name }} state=present
#     with_items:
#       - name: MariaDB
#       - name: MariaDB-server
#       - name: MySQL-python

#   tags: mariadb

- hosts: balancer
  become: true

  tasks:
   - name: updating the system
     yum: update_cache=yes



   - name: Install epel release
     yum:
        name: epel-release
        state: present

   - name: Install nginx
     yum:
        name: nginx
        state: present

   - name: Start nginx
     command: systemctl start nginx

# - name: Copy rpm file to server
#   copy:
#      src: package.rpm
#      dest: /tmp/package.rpm

- name: web server install
  hosts: web_server
  become: true

  tasks:
   - name: enable remi-php72
     shell: yum-config-manager --enable remi-php72

   - name: Install package.
     yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

   - name: Install remi repo.
     yum:
      name:
       - yum-plugin-fastestmirror
       - epel-release
       - httpd
       - php
       - php-common
       - php-mysqli
       - php-mysqlnd
       - php-pgsql
       - php-pear
       - php-mcrypt
       - php-cli
       - php-gd
       - php-curl
       - php-mbstring
       - php-xmlrpc
       - php-soap
       - php-ldap 
       - php-zip 
       - php-fileinfo 
       - php-xml 
       - php-intl
      state: latest
      update_cache: yes
 
   - name: Start service httpd, if not started
     service:
       name: httpd
       state: started
#  - name: write the apache config file
#    template:
#      src: /vagrant/httpd.j2
#      dest: /etc/httpd.conf

   - name: Replace apache config
     replace:
       path: /etc/httpd/conf/httpd.conf
       regexp: '(DocumentRoot "/var/www/html")'
       replace: 'DocumentRoot "/var/www/html/moodle"'


   - name: Restart service httpd, in all cases
     service:
       name: httpd
       state: restarted

   - name: Download file from a file path
     get_url:
       url: https://download.moodle.org/download.php/direct/stable36/moodle-latest-36.tgz
       dest: /home/vagrant/moodle-latest-36.tgz
 
   - name: Extract foo.tgz into /var/lib/foo
     unarchive:
       src: /home/vagrant/moodle-latest-36.tgz
       dest: /var/www/html
