---
- name: web server install
  hosts: web_server
  become: true
  gather_facts: true

  tasks:

   - name: Install apache.
     yum:
      name:
       - yum-plugin-fastestmirror
       - epel-release
       - httpd
       - policycoreutils-python

      state: latest

   - name: Start service httpd, if not started
     service:
       name: httpd       
       state: started
       enabled: yes

   - name: Install remi.
     yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
#     update_cache: yes


   - name: enable remi-php72
     shell: yum-config-manager --enable remi-php72

   - name: Install php.
     yum:
      name:
       - php
       - php-common
       - php-mysqli
       - php-mysqlnd
       - php-pgsql
       - php-pear
       - php-mcrypt
       - php-cli
       - php-gd
       - php-curl
       - php-mbstring
       - php-xmlrpc
       - php-soap
       - php-ldap 
       - php-zip 
       - php-fileinfo 
       - php-xml 
       - php-intl
      state: latest
      update_cache: yes
 

#  - name: write the apache config file
#    template:
#      src: /vagrant/httpd.j2
#      dest: /etc/httpd.conf

   - name: Replace apache config
     replace:
       path: /etc/httpd/conf/httpd.conf
       regexp: 'DirectoryIndex index.html'
       replace: 'DirectoryIndex index.php index.html index.htm'

   - name: Restart service httpd, in all cases
     service:
       name: httpd
       state: restarted

#   - name: Download file from a file path
#     get_url:
#       url: https://download.moodle.org/download.php/direct/stable36/moodle-latest-36.tgz
#       dest: /home/vagrant/moodle-latest-36.tgz
 
   - name: Extract moodle-latest-36.tgz into /var/www/html
     unarchive:
#       src: /home/vagrant/moodle-latest-36.tgz
       src: https://download.moodle.org/download.php/direct/stable36/moodle-latest-36.tgz
       dest: /var/www/html
       owner: apache
       group: apache
       remote_src: yes

   - name: Replace apache config
     replace:
       path: /etc/httpd/conf/httpd.conf
       regexp: 'DocumentRoot "/var/www/html"'
       replace: 'DocumentRoot "/var/www/html/moodle"'

   - name: Replace apache config
     replace:
       path: /etc/httpd/conf/httpd.conf
       regexp: 'DirectoryIndex index.html'
       replace: 'DirectoryIndex index.php index.html index.htm'
      

   - name: Creates directory /var/moodledata
     file:
       path: /var/moodledata
       state: directory
       owner: apache
       group: apache
#       mode: 0755


   - name: Allow apache to modify files in /var/moodledata
     sefcontext:
       target: '/var/moodledata(/.*)'
       setype: httpd_sys_rw_content_t
       reload: True
       state: present

   - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
     seboolean:
       name: httpd_can_network_connect
       state: yes
       persistent: yes

  
   - name: Install Moodle
     command: php admin/cli/install.php
      --lang=en
      --dbtype=mariadb
      --wwwroot=http://{{ ansible_eth1.ipv4.address }}/
      --dataroot=/var/moodledata
      --dbhost={{ BASEHOST }}
      --dbname={{ MAINDB }}
      --dbuser={{ USERDB }}
      --dbpass={{ PASSWDDB }}
      --adminuser=admin
      --adminpass=Admin1
      --fullname='Moodle'
      --shortname=moodle
      --non-interactive
      --allow-unstable
      --agree-license
      --adminemail='example@example.com'
      --summary='Moodle'
      #  {% if moodle_db_import is defined and moodle_version > 2.9 %}
      #    --skip-database
      #  {% endif %}
     args:
       chdir: "/var/www/html/moodle/"
       creates: config.php
     delegate_to: node1
     notify:
       - restart httpd

   - name: Pushes configuration
     template: src=templates/config.php.j2 dest=/var/www/html/moodle/config.php mode=755 owner=apache group=apache
     notify:
       - restart httpd

  handlers:
   - name: restart httpd
     service: name=httpd state=restarted
     
  #  - name: Creates directory /var/www/html/moodle/
  #    file:
  #      path: /var/www/html/moodle/
  #      state: directory
  #      owner: apache

  #      group: apache
  #      mode: 0755